version: '3.4'

services:
  calltracking.fsconsumerworker:
    image: ${DOCKER_REGISTRY-}calltrackingfsconsumerworker
    container_name: fs-consumer-worker
    build:
      context: .
      dockerfile: CallTracking.FSConsumerWorker/Dockerfile

  freeswitch:
    hostname: freeswitch
    container_name: freeswitch
    image: ${DOCKER_REGISTRY-}freeswitch
    build:
      context: Voice/FreeSWITCH
      dockerfile: Dockerfile
